# Generated by Django 3.0.8 on 2020-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlibro', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('stock', models.IntegerField()),
                ('idautores', models.IntegerField()),
                ('ideditorial', models.IntegerField()),
                ('idpais', models.IntegerField()),
            ],
        ),
    ]
